language:
- zh-CN
- en

menu:
  主页: /
  归档: /archives
  工具: /Instrument
  关于我: /AboutMe

widgets:
- github
- category
- recent_posts
- tagcloud


excerpt_link: 继续阅读>>

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: false

fancybox: true

google_analytics:
rss:

comment_provider: facebook

# github info
github_user_name: wenyuking

duoshuo_shortname: wenyuking

tag_color: ["#41BCA4","#A5ED53","#FFFD91","#FFD353","#FF7268","#F3456D","#F4D95B","#95B55B","#F49930","#F26D26"]